### ISSUE TITLE
circle-strafe

### ISSUE THREAD

**Issue by Zuzie-isHere** [qwertyuiop3/Segregation#10]
No problem at all, I just wanted to ask you what you think about my attempt at implementing circle strafing. At the moment, it's not working, but at least I've made some progress. I still need to review more things; honestly, I haven't learned how to program, but I'm doing this in my free time and trying out different things. :P thanks in advice <3
[Circlestrafe-test.txt](https://github.com/qwertyuiop3/Segregation/files/13881288/Circlestrafe-test.txt)

**Comment by qwertyuiop3** [comment]
> What you think about my attempt at implementing circle strafing.

collision should be taken into account
> At the moment, it's not working

- "Circle_Strafe_Angle" is constant so direction will remain same unless you "unconstant" it
- what you're doing with Move (2-dimensional, velocity (actually just component) vectors) is illustrating 2-dimensional circle
- what you're doing with Move_Angles (3-dimensional, euler (tait-bryan) angles) is illustrating 2-dimensional circle

i see that my explanation isn't very clear (you should visualize it then you will see what i mean) but should be enough to understand what is wrong now
```
//static so it doesn't resets everytime
static float Circle_Strafe_Angle;
//angle translated to direction and scaled by 400 (full length)
Command->Move[0] = __builtin_cosf(Circle_Strafe_Angle * 3.1415927f / 180) * 400;
Command->Move[1] = __builtin_sinf(Circle_Strafe_Angle * 3.1415927f / 180) * 400;
//increment strafe angle by optimal value then put it within [0, 360] range
Circle_Strafe_Angle = __builtin_remainderf(Circle_Strafe_Angle + __builtin_atan2f(30, __builtin_hypotf(Velocity[0], Velocity[1])) * 180 / 3.1415927f, 360);
```
"Move_Angles[0]" is up/down within [0, 360] (limited to [-90, 90] by game) range (definitely not what you need for circle strafe)
![](https://upload.wikimedia.org/wikipedia/commons/e/ec/Aileron_pitch.gif)
"Move_Angles[1]" is right/left within [0, 360] range (exactly what you need for circle strafe)
![](https://upload.wikimedia.org/wikipedia/commons/9/96/Aileron_yaw.gif)
"Move_Angles[2]" is circular rotation (left/right) around Move_Angles within [0, 360] range (also not what you need)
![](https://upload.wikimedia.org/wikipedia/commons/c/cc/Aileron_roll.gif)

"Move[0]" is back/forward within [-400, 400] range
"Move[1]" is left/right within [-400, 400] range
![](https://upload.wikimedia.org/wikipedia/commons/6/64/Unit_Vector_2D_anim.gif)

so alternative solution would be
```
//static so it doesn't resets everytime
static float Circle_Strafe_Angle;
//strafe direction
Command->Move[1] = -400;
//strafe angle
Move_Angles[1] = Circle_Strafe_Angle;
//increment strafe angle by optimal value then put it within [0, 360] range
Circle_Strafe_Angle = __builtin_remainderf(Circle_Strafe_Angle + __builtin_atan2f(30, __builtin_hypotf(Velocity[0], Velocity[1])) * 180 / 3.1415927f, 360);
```
also my bad [attempt](https://github.com/qwertyuiop3/Segregation/commit/b972e8a70d94e3a375e4cc7c9f900009beb68cf0#commitcomment-95353369) at circle strafing (checking collision by simulation + distance)

**edit**

to not disinform you actual limitations are:
- down/up limitation is defined by cl_pitchdown and cl_pitchup cvars
- back/forward/left/right limitation is defined by cl_backspeed, cl_forwardspeed, cl_sidespeed, sv_maxspeed, sv_maxvelocity and MaxPlayerSpeed (from weapon_*.ctx)

**Comment by Zuzie-isHere** [comment]
After a long time trying and thinking I managed to do that :P

(https://gist.github.com/Zuzie-isHere/fa7f1b973f739232c6ae3287d1476315)

Please don't be dismissive about it since I literally know nothing about c++ or programming languages and I've been trying to understand a little of what you told me.

About the errors:
The two errors I see are that the circle strafe is always active, and besides, it tends to collide with walls or structures after a while. Additionally, it crashes when there is a player in the game. Anyway, I think I did quite well for my first time trying to learn something about this.

Thanks  ❤️

Edit: I managed to fix the issue where it would constantly circle-strafe when jumping; now it only circle-strafes if I press ALT. also it tends to collide with walls or structures after a while.

Edit 2: the crash is fixed i forget to remove // in bruteforce  :P
