### ISSUE TITLE
How do i install it?

### ISSUE THREAD

**Issue by BrayHax** [qwertyuiop3/Segregation#15]
How can i install the cheat as dll? i cant find any release or something like that, maybe im just slow but whatever

**Comment by Zuzie-isHere** [comment]
To get segregation, you need download Microsoft Visual Studio from https://visualstudio.microsoft.com/en/.

Then, you need download the necessary libraries to compile segregation.

Finally, within the application, click on compile.

If your computer doesn't have enough space or you simply don't want to download Microsoft Visual Studio, you can add me on Discord, and I'll compile it for you. I'll share my screen throughout the process to make everything transparent.

Discord: iloveduck_s1
