### ISSUE TITLE
Inquiry about the sound system and menu implementation options in Segregation

### ISSUE THREAD

**Issue by Zuzie-isHere** [qwertyuiop3/Segregation#17]
Hello,

After some time away, I’m back to make a few inquiries and would like to start by sincerely thanking you for all the help you provided before. Your support has been invaluable.

I have a couple of questions that I’d like to resolve:

How does the sound system work in Segregation? In relation to the first question, would it be possible to add sounds at the start and end of each round? I’d also like to know if it’s possible to add sounds for specific actions, like deactivating a bomb, the bomb exploding, or stabbing someone.

Additionally, I’m considering implementing a menu in my project and would like your opinion on the best way to do it. Would you recommend using ZGUI, ImGui, or another solution for the graphical interface? I’ve tried using ImGui to create a duck-shaped menu in Segregation, which is controlled by clicking certain areas to activate functions and holding the click to adjust features. However, I’ve noticed a significant decrease in FPS, possibly due to my inexperience.

Thank you in advance for your time and any advice you can offer.

Edit:

Following up on these topics, I’ve been considering the possibility of handling the sound-related functionality within event_processor.hpp. However, I’m finding it a bit challenging to understand how sound.hpp works, which is affecting my ability to import sounds properly. I believe it would be beneficial to create a more detailed event_processor to address this issue. I would appreciate your thoughts on this approach.

Additionally, I’m working on an HVH plugin and have a question about integrating it with the server. Specifically, I am interested in whether it’s possible to incorporate some functionality of the cheat directly with the server. My goal is to detect if a player is using a Segregation version when they join the server and display this information in the stats bar. Although I could potentially implement this myself, I am concerned that it might be easily bypassed if someone is using a paste. My idea is to ensure that the system can detect even if a player is using a paste or a fork of Segregation, and accurately reflect this in the stats bar.

Thank you in advance for your time and any advice you can offer.

edit 2: i reworked the sound

**Comment by qwertyuiop3** [comment]
> How does the sound system work in Segregation?

it takes bytecode of waveform (.wav) file from array of bytes; "HxD" supports bytecode export

> Would it be possible to add sounds at the start and end of each round?

that would require adding listeners for "round_start", "round_end" and accordingly filtering event in "Event_Processor" by name

> I’d also like to know if it’s possible to add sounds for specific actions, like deactivating a bomb, the bomb exploding, or stabbing someone

listen to:
- https://wiki.alliedmods.net/Counter-Strike:_Source_Events#bomb_defused
- https://wiki.alliedmods.net/Counter-Strike:_Source_Events#bomb_exploded
- https://wiki.alliedmods.net/Counter-Strike:_Source_Events#player_death

regarding stabbing: to determine if weapon_knife is used `Event->GetString("weapon", nullptr)` must be called

> Would you recommend using ZGUI, ImGui, or another solution for the graphical interface?

i do not have sympathy towards any of premade graphical solutions (both are failing at calculating font dimensions precisely). creating own is preferable for better understanding

> I’ve tried using ImGui to create a duck-shaped menu in Segregation, noticed a significant decrease in FPS

i can't really guess what is reason behind FPS drop, but you could take look at vector graphics (depending on complexity of shape) for better performance

> I am interested in whether it’s possible to incorporate some functionality of the cheat directly with the server

one of ways to send signals to server is through "CUserCmd" members, by manipulating them in "Copy_Command.hpp" and processing them later in: https://sm.alliedmods.net/new-api/sdktools_hooks/OnPlayerRunCmd

> My idea is to ensure that the system can detect even if a player is using a paste or a fork of Segregation, and accurately reflect this in the stats bar.

there is no fail-proof way of detecting forks.

some of possible detections:
- QueryClientConVar
- non-zero upmove (vel[2] in sm)
- heuristics towards specific pattern in f/s/u-move (vel)
- invalid m_nBackupCommands (requires extensions)
- roll nospread
- ...

**Comment by Zuzie-isHere** [comment]
I want to express my sincere gratitude for taking the time to answer all my questions in detail, especially given that I opened 6 tickets. The Counter-Strike Source development community is quite inactive, so I didn’t expect such thorough responses.

Throughout our interaction, you’ve shown great respect. When you couldn’t respond immediately, you kindly apologized and explained your delay. From the beginning, you informed me of your availability and asked for patience, which I truly appreciate.

I spend my free time working on Counter-Strike: Source projects, adding fun or customized features, whether new ideas or improvements on existing concepts. While some friends and acquaintances are aware of my work, they often show disinterest or even mock my questions, which can be discouraging. Your support stands out as a positive contrast to these experiences.

Thank you once again for your kindness and patience. Your support has been invaluable to me. I also apologize if I seem repetitive; respectful communication is rare for me, and I truly value it. I hope not to trouble you further, but your positive attitude is deeply appreciated.
