### ISSUE TITLE
Failure to compile project animation.hpp client module is not defined

### ISSUE THREAD

**Issue by Zuzie-isHere** [qwertyuiop3/Segregation#6]
in the file update animation.hpp the client module is not defined
![image](https://github.com/qwertyuiop3/Segregation/assets/36802199/7ea08294-9190-4178-8e78-e6ceab9e97f3)

**Comment by qwertyuiop3** [comment]
should be working now. i was blindly syncing changes between no-steam and steam

**Comment by lekobru** [comment]
Заздроснити как у тибя дила

чт, 28 дек. 2023 г., 03:18 qwertyuiop3 ***@***.***>:
