### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Zuzie-isHere** [qwertyuiop3/Segregation#7]
In the compilation, everything is fine, and there are no issues even when opening the .cpl file. However, when attempting to connect to a local server or an internet server, the game automatically closes.

**Comment by Zuzie-isHere** [comment]
crash problem fixed here a picture of what the problem was (it was not solved by me but by a friend) 
![image](https://github.com/qwertyuiop3/Segregation/assets/36802199/499a0a67-6158-463b-af5a-13c0c7999536)

**Comment by qwertyuiop3** [comment]
just update your repository "git pull" it's [solved](https://github.com/qwertyuiop3/Segregation/commit/e3965d3ce65763abfb21a27426d8c68fd93aa34d) 3 days ago
